apiVersion:  apps/v1
kind : Deployment
metadata :
 name: auth
spec:
  replicas: 3
  selector:
    matchLabels :
      app: auth
  template:
   metadata:
    labels:
     app: auth
   spec:
    containers:
     - name: auth
       image: isayasone/ordering-app-auth
       ports:
        - containerPort: 3001
       env:
        - name: PORT
          value: '3001'
        - name: RABBIT_MQ_BILLING_QUEUE
          value: billing
        - name: JWT_EXPIRATION
          value: '3600'
        - name: JWT_SECRET
          value: yJSDVpxKUQ1LSfrnrsLN6r6tmFd1i95I3zGXjpIryO8zoWg7fDmYEnyyCmtKFh2MFd4c7rFjN9wKsiwRXYKZ9BKJ5YHTByQi8Q4
        - name: RABBIT_MQ_AUTH_QUEUE
          value: auth
        - name: MONGODB_URI
          value: mongodb://root:password321@ordering-app-ordering-app-mongodb-headless:27017
        - name: RABBIT_MQ_URI
          value: amqp://user1:password321@ordering-app-rabbitmq:5672






