apiVersion: apps/v1
kind : Deployment
metadata :
 name: orders
spec:
  replicas: 3
  selector:
    matchLabels:
      app: orders
  template:
   metadata:
    labels:
     app: orders
   spec:
    containers:
     - name: orders
       image: isayasone/ordering-app-orders
       ports:
        - containerPort: 3001
       env:
        - name: PORT
          value: '3000'
        - name: RABBIT_MQ_BILLING_QUEUE
          value: billing
        - name: RABBIT_MQ_AUTH_QUEUE
          value: auth
        - name: MONGODB_URI
          value: mongodb://root:password321@ordering-app-ordering-app-mongodb-headless:27017
        - name: RABBIT_MQ_URI
          value: amqp://user1:password321@ordering-app-rabbitmq:5672









